Repository cucumber-rs/cucumber, pull requests merged in 2021-12, with the labels that each got.

#165 Add tags from Examples to Scenario Outline (#164)
  CHANGELOG.md
  Cargo.toml
  src/feature.rs
  tests/features/output/ambiguous_step.feature.out
  tests/features/output/background_rule.feature.out
  tests/features/output/background_rule_background.feature.out
  tests/features/output/background_rule_background_outline.feature.out
  tests/features/output/background_rule_outline.feature.out
  tests/features/output/background_scenario.feature.out
  tests/features/output/background_scenario_outline.feature.out
  tests/features/output/non_default_lang.feature.out
  tests/features/output/rule.feature.out
  tests/features/output/rule_background.feature.out
  tests/features/output/rule_background_outline.feature.out
  tests/features/output/rule_outline.feature.out
  tests/features/output/scenario.feature.out
  tests/features/output/scenario_outline.feature.out
  tests/features/output/scenario_outline_adjacent_templates.feature.out
  tests/features/output/scenario_outline_table.feature.out
  tests/features/output/scenario_outline_with_multiple_examples.feature
  tests/features/output/scenario_outline_with_multiple_examples.feature.out
  tests/features/output/scenario_outline_with_tags.feature
  tests/features/output/scenario_outline_with_tags.feature.out
  tests/features/wait/outline.feature
  tests/json/correct.json
Labels: enhancement

#170 Fix regex capturing group in JUnit test
  tests/junit.rs
Labels: bug

#178 Expand Docstrings and names in Scenario Outline (#172)
  CHANGELOG.md
  codegen/src/attribute.rs
  src/feature.rs
  tests/features/output/background_rule_background_outline.feature
  tests/features/output/background_rule_background_outline.feature.out
  tests/features/output/scenario_outline_with_basic_dosctring.feature
  tests/features/output/scenario_outline_with_basic_dosctring.feature.out
  tests/features/output/scenario_outline_with_expanded_dosctring.feature
  tests/features/output/scenario_outline_with_expanded_dosctring.feature.out
Labels: enhancement

#180 Fix broken link
  book/src/Test_Modules_Organization.md
Labels: documentation

#182 Implement `writer::AssertNormalized`
  CHANGELOG.md
  src/writer/mod.rs
  src/writer/normalize.rs
  src/writer/summarize.rs
Labels: enhancement

#181 Rename `@allow_skipped` built-in tag to `@allow.skipped`
  CHANGELOG.md
  Cargo.toml
  book/src/Test_Modules_Organization.md
  codegen/tests/features/doctests.feature
  src/cucumber.rs
  src/writer/fail_on_skipped.rs
  src/writer/mod.rs
  tests/features/output/feature_description_with_allowed_keywords.feature
  tests/features/output/feature_description_with_allowed_keywords.feature.out
  tests/features/output/scenario_outline_with_tags_and_comments.feature
  tests/features/output/scenario_outline_with_tags_and_comments.feature.out
  tests/features/wait/invalid.feature
Labels: enhancement

#189 Fix `writer:: Summarize` ignoring `Coloring` options (#186)
  CHANGELOG.md
  src/cli.rs
  src/writer/basic.rs
  src/writer/out.rs
  src/writer/summarize.rs
Labels: enhancement

#188 Replace structopt by clap (#155)
  CHANGELOG.md
  Cargo.toml
  src/cli.rs
  src/cucumber.rs
  src/parser/basic.rs
  src/parser/mod.rs
  src/runner/basic.rs
  src/runner/mod.rs
  src/writer/basic.rs
  src/writer/mod.rs
  tests/wait.rs
Labels: enhancement

#193 Add `verbose` CLI flag to the `writer::Basic` (#192)
  CHANGELOG.md
  book/src/cli.md
  book/src/output/junit.md
  book/src/output/terminal.md
  book/src/quickstart.md
  book/src/rec/cli_custom.gif
  book/src/rec/output_terminal_repeat_failed.gif
  book/src/rec/output_terminal_verbose.gif
  book/src/rec/output_terminal_verbose_1.gif
  book/src/rec/output_terminal_verbose_2.gif
  book/src/rec/quickstart_simple_fail.gif
  book/src/rec/writing_asserting_panic.gif
  book/src/rec/writing_asserting_result.gif
  book/src/rec/writing_doc_strings.gif
  book/src/rec/writing_tags_skip.gif
  book/src/writing/asserting.md
  book/src/writing/doc_strings.md
  src/writer/basic.rs
  src/writer/discard.rs
  src/writer/json.rs
  src/writer/junit.rs
  src/writer/mod.rs
  tests/junit.rs
Labels: enhancement
