Repository cucumber-rs/cucumber, pull requests merged in 2022-11, with the labels that each got.

#238 Add `Clone` implementations to all public types, where possible
  CHANGELOG.md
  src/cli.rs
  src/cucumber.rs
  src/parser/basic.rs
  src/runner/basic.rs
  src/step.rs
  src/writer/basic.rs
  src/writer/fail_on_skipped.rs
  src/writer/junit.rs
  src/writer/libtest.rs
  src/writer/normalize.rs
  src/writer/out.rs
  src/writer/repeat.rs
  src/writer/summarize.rs
Labels: enhancement

#239 Switch from `skeptic` to `mdbook test`
  .github/workflows/ci.yml
  Cargo.toml
  Makefile
  book/README.md
  book/src/architecture/parser.md
  book/src/architecture/runner.md
  book/src/architecture/writer.md
  book/src/cli.md
  book/src/introduction.md
  book/src/output/intellij.md
  book/src/output/json.md
  book/src/output/junit.md
  book/src/output/multiple.md
  book/src/output/terminal.md
  book/src/quickstart.md
  book/src/writing/asserting.md
  book/src/writing/background.md
  book/src/writing/capturing.md
  book/src/writing/data_tables.md
  book/src/writing/doc_strings.md
  book/src/writing/hooks.md
  book/src/writing/languages.md
  book/src/writing/retries.md
  book/src/writing/rule.md
  book/src/writing/scenario_outline.md
  book/src/writing/tags.md
  book/tests/Cargo.toml
  book/tests/build.rs
  book/tests/src/lib.rs
Labels: enhancement, k::toolchain, k::testing

#240 Fix mdBook tests on Windows
  .github/workflows/ci.yml
  Makefile
  book/README.md
  src/lib.rs
Labels: enhancement, k::toolchain, k::testing

#242 Fix hanging with fail-fast option (#241)
  CHANGELOG.md
  Cargo.toml
  book/src/cli.md
  src/runner/basic.rs
  tests/fail_fast.rs
  tests/features/fail_fast/no_retry.feature
  tests/features/fail_fast/retry.feature
  tests/features/fail_fast/retry_delayed.feature
Labels: enhancement, k::testing, k::refactor, k::UI/UX

#246 Pass `event::ScenarioFinished` to after hook handler (#245)
  CHANGELOG.md
  book/src/writing/hooks.md
  src/cucumber.rs
  src/event.rs
  src/runner/basic.rs
  tests/after_hook.rs
  tests/json.rs
  tests/wait.rs
Labels: enhancement, k::documentation, breaking, k::api
